"""Physical constants, verbatim from share/util/shr_const_mod.F90 and
the derivations in eam/src/utils/physconst.F90 (see the f2py stub
harness/stubs/physconst_stub.F90, which is compiled against the real
shr_const_mod and is the source of truth for the goldens)."""

SHR_CONST_PI = 3.14159265358979323846
SHR_CONST_BOLTZ = 1.38065e-23
SHR_CONST_AVOGAD = 6.02214e26
SHR_CONST_RGAS = SHR_CONST_AVOGAD * SHR_CONST_BOLTZ
SHR_CONST_MWDAIR = 28.966
SHR_CONST_MWWV = 18.016
SHR_CONST_RDAIR = SHR_CONST_RGAS / SHR_CONST_MWDAIR
SHR_CONST_RWV = SHR_CONST_RGAS / SHR_CONST_MWWV
SHR_CONST_G = 9.80616
SHR_CONST_STEBOL = 5.670374419e-8
SHR_CONST_KARMAN = 0.4
SHR_CONST_TKTRIP = 273.16
SHR_CONST_TKFRZ = 273.15
SHR_CONST_CPDAIR = 1.00464e3
SHR_CONST_CPWV = 1.810e3
SHR_CONST_CPFW = 4.188e3
SHR_CONST_LATICE = 3.337e5
SHR_CONST_LATVAP = 2.501e6
SHR_CONST_LATSUB = SHR_CONST_LATICE + SHR_CONST_LATVAP
SHR_CONST_RHOFW = 1.000e3
SHR_CONST_PSTD = 101325.0

# physconst derivations
AVOGAD = SHR_CONST_AVOGAD
BOLTZ = SHR_CONST_BOLTZ
CPAIR = SHR_CONST_CPDAIR
CPWV = SHR_CONST_CPWV
EPSILO = SHR_CONST_MWWV / SHR_CONST_MWDAIR
GRAVIT = SHR_CONST_G
H2OTRIP = SHR_CONST_TKTRIP
KARMAN = SHR_CONST_KARMAN
LATICE = SHR_CONST_LATICE
LATVAP = SHR_CONST_LATVAP
LATSUB = SHR_CONST_LATSUB
MWDRY = SHR_CONST_MWDAIR
MWH2O = SHR_CONST_MWWV
RAIR = SHR_CONST_RDAIR
RGAS = SHR_CONST_RGAS
RH2O = SHR_CONST_RWV
RHOH2O = SHR_CONST_RHOFW
STEBOL = SHR_CONST_STEBOL
TMELT = SHR_CONST_TKFRZ
ZVIR = SHR_CONST_RWV / SHR_CONST_RDAIR - 1.0
CAPPA = SHR_CONST_RDAIR / SHR_CONST_CPDAIR
CPVIR = SHR_CONST_CPWV / SHR_CONST_CPDAIR - 1.0
PSTD = SHR_CONST_PSTD
